spring:
  datasource:
    url: jdbc:mysql://localhost:3306/finguard_db
    username: finguard_user
    password: finguard_pass
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update   # or 'create' during development
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

  # Optional: prevent console warnings
  sql:
    init:
      mode: always

server:
  port: 8081
